### ISSUE TITLE
win 10 上不行 ？

### ISSUE THREAD

**Issue by gflkdns** [wulio/Coeus#2]
Microsoft Windows [版本 10.0.17763.652]                               
                                                                    
miqt@DESKTOP-98UF1SJ E:\Coeus                                       
$ python coeus.py /test/analysys_track_v4.3.0.6_2019121300.jar      
root        : INFO     start sdk scan..                             
root        : ERROR    sdk文件不存在                                     
                                                                    
miqt@DESKTOP-98UF1SJ E:\Coeus                                       
$

**Comment by wulio** [comment]
> Microsoft Windows [版本 10.0.17763.652]
> 
> miqt@DESKTOP-98UF1SJ E:\Coeus
> $ python coeus.py /test/analysys_track_v4.3.0.6_2019121300.jar
> root : INFO start sdk scan..
> root : ERROR sdk文件不存在
> 
> miqt@DESKTOP-98UF1SJ E:\Coeus
> $

建议尝试用绝对路径，当前相对路径提示找不到此jar文件
--考虑后续版本会支持相对路径的~预计月底更新吧

**Comment by gflkdns** [comment]
好的，了解
